#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'robo-entrega-provide-map','console_scripts','load_map_client'
__requires__ = 'robo-entrega-provide-map'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('robo-entrega-provide-map', 'console_scripts', 'load_map_client')()
    )
