#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'robo-entrega-nav2-system','console_scripts','initial_pose_pub'
__requires__ = 'robo-entrega-nav2-system'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('robo-entrega-nav2-system', 'console_scripts', 'initial_pose_pub')()
    )
